### ISSUE TITLE
releng

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging-schemas-issues#11]

**Comment by ryanlerch** [comment]
Does anyone have any idea what this one actually is? WE def need some more information here.

**Comment by ryanlerch** [comment]
@pypingou any idea what this one could be?

**Comment by pypingou** [comment]
These corresponds to https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/releng.py

We should check with @mohanboddu  if they are still in used

**Comment by pypingou** [comment]
I suspect the script sending these messages is https://pagure.io/releng/blob/master/f/scripts/push-two-week-atomic.py

@humaton @mohanboddu do you still use it ^?

**Comment by mohanboddu** [comment]
@pypingou We are not using that script anymore. Its been dead since we moved to CoreOS.

**Comment by ryanlerch** [comment]
Thanks @mohanboddu @pypingou . Going to close this one off now.
