### ISSUE TITLE
kerneltest

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging-schemas-issues#25]

**Comment by ryanlerch** [comment]
Kerneltest prod:
https://apps.fedoraproject.org/kerneltest/

Wikipage about it: 
https://fedoraproject.org/wiki/KernelTestingInitiative


The Source of kerneltest  is available here:
https://github.com/jmflinuxtx/kerneltest-harness

**Comment by ryanlerch** [comment]
AFICT, kerneltest doesnt actually send any messages, it only consumes messages (from koji) -- so i think there is actually nothing to do here.

https://github.com/jmflinuxtx/kerneltest-harness/blob/master/kerneltest/harness.py#L32
