### ISSUE TITLE
Add schemas to koji

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging-schemas-issues#3]

**Comment by cverna** [comment]
I started some work there https://pagure.io/koji-fedmsg-plugin/blob/master/f/koji_fedmsg_plugin/messages

**Comment by ryanlerch** [comment]
@cverna the schemas here look pretty comphensive. what else was there to be done on this?

**Comment by pypingou** [comment]
@cverna did you see Ryan's question? Is there anything remaining for koji's schemas?

**Comment by cverna** [comment]
Sorry missed the ping from Ryan. I think what is still needed is do the rpm packaging for it so that we can use these schemas.

**Comment by pypingou** [comment]
So it's basically ready and needs to be packaged to be deployed and used?

**Comment by cverna** [comment]
> So it's basically ready and needs to be packaged to be deployed and used?

The plugin was not changed to use the schema when sending the messages, I thought that it would be better to do the packaging first.

So I would say that what is left is 
- add the messages schema to the rpm package
- update the plugin code to use the schema for sending messages.

**Comment by nphilipp** [comment]
Fixed in fedora-infra/koji-fedoramessaging-messages#1 and fedora-infra/koji-fedoramessaging-messages#2
